<?php
/**
 * Implements hook_field_formatter_info().
 */
function html5_media_field_formatter_info() {
  return array(
    'html5_audio' => array(
      'label' => t('Audio'),
      'description' => t('Play this file as audio.'),
      'field types' => array('file'),
      'settings' => array(
        'controls' => TRUE,
        'preload' => TRUE,
        'autoplay' => FALSE,
        'loop' => FALSE
      )
    ),    
    'html5_video' => array(
      'label' => t('Video'),
      'description' => t('Display this file as a video.'),
      'field types' => array('file'),
      'settings' => array(
        'controls' => TRUE,
        'preload' => TRUE,
        'autoplay' => FALSE,
        'loop' => FALSE
      )
    )
  );
}

/**
 * Implements hook_field_formatter_settings_form
 */
function html5_media_field_formatter_settings_form($field, $instance, $view_mode, $form, &$form_state) {
  $display = $instance['display'][$view_mode];
  $settings = $display['settings'];
  $element = array();
  if (($display['type'] == 'html5_audio') || ($display['type'] == 'html5_video')) {
    
    $element['preload'] = array(
      '#title' => t('Preload'),
      '#type' => 'checkbox',
      '#default_value' => $settings['preload']
    );
    
    $element['autoplay'] = array(
      '#title' => t('Autoplay'),
      '#type' => 'checkbox',
      '#default_value' => $settings['autoplay']
    );
    
    $element['loop'] = array(
      '#title' => t('Loop'),
      '#type' => 'checkbox',
      '#default_value' => $settings['loop']
    );  
    
    $element['combine'] = array(
      '#title' => t('Combine'),
      '#type' => 'checkbox',
      '#default_value' => $settings['combine']
    );
  }
  return $element;
}

/**
 * Implements hook_field_formatter_settings_summary
 */
function html5_media_field_formatter_settings_summary($field, $instance, $view_mode) {
  $display = $instance['display'][$view_mode];
  $settings = $display['settings'];
  $summary = '';
  if (($display['type'] == 'html5_audio') || ($display['type'] == 'html5_video')) {
    $header = array('Setting', 'Value');
    $rows = array();
    foreach ($settings as $name => $value) {
      $rows[] = array($name, $value);
    }
    $summary = theme('table', array('header' => $header, 'rows' => $rows));
  }
  return $summary;
}

/**
 * Returns the settings for this video or audio element.
 */
function html5_media_get_attributes($item, $settings) {
  $attributes = array();
  $attributes['src'] = file_create_url($item['uri']);
  foreach ($settings as $name => $value) {
    if ($value) {
      $attributes[$name] = NULL;
    }
  }
  return $attributes;
}

/**
 * Implements hook_field_formatter_view().
 */
function html5_media_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $settings = $display['settings'];  
  $attributes = array();
  switch ($display['type']) {
    case 'html5_audio':
      $sources = array();
      foreach ($items as $delta => $item) {
        //dsm($item);
        $sources[] = file_create_url($item['uri']);
      }

       $element[0] = array(
         '#theme' => 'audio',
         '#tag' => 'audio',
         '#attributes' => array('controls' => 'controls'),
         '#sources' => $sources,
       );

      break;
  }
  return $element;
}

/**
 * Implements hook_theme().
 */
function html5_media_theme ($existing, $type, $theme, $path) {
  return array(
    'audio' => array(
      'render element' => 'element',
    ),
  );
}

/*
 * Implements theme()
 */
function theme_audio($variables) {
  $element = $variables['element'];
  _form_set_class($element, array('html5-audio'));

  return '<audio ' . drupal_attributes($element['#attributes']) . '>' . form_audio_options($element) . 'Your browser does not support the audio element.</audio>';
}

/**
 * Implements form_select_options()
 */
function form_audio_options($element, $sources = NULL) {
  if (!isset($sources)) {
    $sources = $element['#sources'];
  }
  $options = '';
  foreach ($sources as $key => $source) {
    $key = (string) $key;
    $options .= '<source src="' . check_plain($source) . '" />';
  }
  return $options;
}
